### ISSUE TITLE
Syntax highlighting for fortran is not satisfying

### ISSUE THREAD

**Issue by ahelm** [dparkins/language-fortran#100]
One issue I discovered recently is quite striking. The issue is, that for most color schemes in Atom, the color scheme for fortran files looks really unsatisfying while for other languages it provides a pleasing highlighting.

For example, let's compare some Fortran code

![image](https://user-images.githubusercontent.com/1353242/29480685-1189df52-842f-11e7-869f-b3a1c83aa16d.png)

and some C code

![image](https://user-images.githubusercontent.com/1353242/29480772-b31e9178-842f-11e7-8cf4-19b725ac8dbb.png)

I am using here the "One Dark" color scheme with Atom 1.19.2. Other schemes have showed similar issues. The issue is that some syntax pieces has a different color and making it less appealing for the eye and less consistency throughout the editor, e.g. variables are highlighted and should not have any highlight. It arises due to the fact, that every syntax matching has it own class and for simple variables a color is applied as Atom assumes that it has specific significance. 

Is it possible to modify the matching of the syntax that the syntax schemes get better aware of specific highlighting? I can modify my local `styles.less` to match specific classes to be not highlighted how they are, but I think a general approach would be helpful and helpful for other users as well. I can also make a pull request and change things, if you wish, but I would appreciate to have your take on that.

**Comment by tomedunn** [comment]
Thanks for posting. Unfortunately, I think this is more likely a bug in the syntax them you're using than this language package. 

To explain, how a color scheme interacts with a language package falls pretty much entirely on the color scheme side of the equation as long as the syntax package is following the standard textmate [scoping convention](http://manual.macromates.com/en/language_grammars), as is the case with language-fortran. I ran a simple test to check that there wasn't something wrong with the scoping

<img width="711" alt="screen shot 2017-08-19 at 1 00 53 am" src="https://user-images.githubusercontent.com/5925666/29483968-34e4c214-847a-11e7-98b2-6ad9000b3ba5.png">

<img width="712" alt="screen shot 2017-08-19 at 1 02 56 am" src="https://user-images.githubusercontent.com/5925666/29483970-3c76c66c-847a-11e7-9706-b32c231d9985.png">

In both cases the scoping for `=` is `keyword.operator.assignment`. The trailing `.c` and `.fortran` should have no impact on the way the color scheme is applied and neither should the `meta` or `source` scopes. So the fact that `=`  is colored differently in both examples points to there being something different in how the "One Dark" theme is being applied to the two different language, which really shouldn't be the case. 

The other main difference between these two cases is how `some_variable` is scoped by this syntax and the C syntax. In the C syntax `some_variable` is not given any scope while for the Fortran syntax it is given the `meta.variable` scope. All scopes that start with `meta` shouldn't be assigned a color. So again, it looks like the "One Dark" theme is doing something strange with their color assignments.

The main theme that I use when testing language-fortran is the "Monokai Seti" theme, shown below

<img width="707" alt="screen shot 2017-08-19 at 1 30 38 am" src="https://user-images.githubusercontent.com/5925666/29484140-0b857a2c-847e-11e7-91b9-c5cde2292167.png">


<img width="710" alt="screen shot 2017-08-19 at 1 31 40 am" src="https://user-images.githubusercontent.com/5925666/29484145-2f0d8660-847e-11e7-975a-8f9ecf50ab23.png">


As you can see the color assignment is much more consistent. The only remaining difference is between the name of the program unit in Fortran and the name of the function unit in C, which is to expected since they are intentionally scoped differently. A fairer comparison would be with a function or subroutine in Fortran as shown below

<img width="715" alt="screen shot 2017-08-19 at 1 29 26 am" src="https://user-images.githubusercontent.com/5925666/29484130-e75b0b62-847d-11e7-80d4-ea892785dc49.png">

**Comment by ahelm** [comment]
Interesting. I tried different syntax schemes and found basically out that, as you said, it depends on the scoping convention and with the default themes it seems to have different conventions each time as it didn't had a consistency. 

Thanks for the clarification.

**Comment by tomedunn** [comment]
language-fortran is a bit more ambitious than most other languages in that it assigns scopes to nearly every element in any given file. However, most of those additional scoped elements are given scopes that shouldn't be highlighted (such as those using the `meta` scope). The fact that so many of the default color schemes seem to actually apply some kind of color, or other emphasis, is a bit concerning. If there's been a move to extend highlighting to scopes beyond the standard Textmate scopes it would be good to know that.
