### ISSUE TITLE
Missing highlight

### ISSUE THREAD

**Issue by cpazinatto** [dparkins/language-fortran#2]
I'm having some problems with the 'do concurrent' statement
do concurrent (i=1:n)
    ! code here
end do
the 'concurrent' part has no highlight.

I'm also having problem with the following lines:

interface setGaussLegendre
        module procedure setGaussLegendre01, setGaussLegendreAB
end interface setGaussLegendre

I always get a highlighted 'end' inside the 'setGaussLegendre01'.

Thanks!

**Comment by elezar** [comment]
The other issue that is mentioned may be related to Issue #20.

**Comment by tomedunn** [comment]
These issues appear to be fixed in version 1.3.1:

![Language-Fortran issue #2 part 1](https://cloud.githubusercontent.com/assets/5925666/5995651/b22e3082-aa5e-11e4-9cef-a33813ddbf1b.png)
and
![Language-Fortran issue #2 part 2](https://cloud.githubusercontent.com/assets/5925666/5995638/58ceeb26-aa5e-11e4-8292-32c8e10292d5.png)
