### ISSUE TITLE
Extension of language

### ISSUE THREAD

**Issue by elezar** [dparkins/language-fortran#26]
In the Fortran code that I develop, we use our own custom preprocessor, and I would like to extend the language-fortran syntax to add support for this, as well as our custom file extensions.

I have tried the simple "include" solution given here: http://stackoverflow.com/questions/22363070/how-do-i-make-a-default-syntax-by-filetype-in-atom-text-editor, but in this case, no highlighting works -- even if I don't yet add the support for the preprocessor directives.

What would be the correct way to go about this?

**Comment by tomedunn** [comment]
@elezar. So this is a much trickier issue than one might think and one I've given a decent amount of thought to in the past.  For a TLDR explanation, the fact that the Modern Fortran rules *insert* into the code imported from Punchcard Fortran prevents you from including Modern Fortran rules in the way they outline in the post you linked. We could get around this by not having Modern Fortran include the Punchcard Fortran source which would really only be a problem in terms of code reusability.

As for a longer explanation, both Fortran grammars try to section the code up into structured blocks like `functions` and `subroutines`, etc. Rules can be added into such structures by either adding them verbatim (writing the rule explicitly in each structure you want it to occur), including them from a repository
```coffee
'patterns':[
  {'include': '#rules'}
]
```
or injecting them
```coffee
'injections':
  'source.fortran':
    'patterns':[
      {'include': '#rules'}
    ]
```
Including rules by and large is the best way of doing this however for some reason in Atom you can't access repositories held in other files. So Modern Fortran can't include rules defined in Punchcard Fortran. It can however add all the Punchcard Fortran rules, i.e.,
```coffee
{'include': 'source.fortran'}
```
and then inject new rules into the rules defined in source.fortran. To further complicate things, and again I'm not sure why Atom chooses to do it this way, rules that are injected aren't ported over from an include statement. Since pretty much all of the rules in Modern Fortran are injected into the included Punchcard Fortran rules, when you try to use `{'include': 'source.fortran.modern'}` it's not going to add anything.

As I mentioned at the start, the best was I can think of to fix this is to completely separate Punchcard from Modern Fortran. At which point all the injected rules in Modern Fortran can simply be included in the regular fashion (I'm honestly not sure what the point of having Punchcard Fortran be it's own separate thing other than keeping things consistent with older version of the grammar).

**Comment by tomedunn** [comment]
@elezar I finally had some time to work on the modifications I mentioned in my earlier post. I need to run more detailed tests before I submit a pull request but you can find them in my forked repository https://github.com/tomedunn/language-fortran. I've included an example of how to include custom preprocessor rules using the preprocessor rules which were included in the original Punchcard - Fortran rules. If you have any questions let me know. Also if you're working on a Mac,  ⌘⌥P will show the scope of the currently selected character.

**Comment by elezar** [comment]
Thanks @tomedunn. I have been afk for the past week, but I will have a look at your proposed changes as soon as I get a chance. Thanks for the effort!
