### ISSUE TITLE
Atom freezes when I start typing the word "Class"

### ISSUE THREAD

**Issue by kgerheiser** [dparkins/language-fortran#37]
I start typing the word "class" and it gets to "clas" and then atom freezes and the Atom Helper process consumes 100% cpu. I've narrowed it down to this package after disabling everything else and then trying them one by one. I've only been using Atom for a few days and it was working fine before and I was able to type the "Class" without issue and it just started. 

It seems to affect all my .f90 files regardless of their directory. I did a fresh install of Atom, making sure to delete the app, preference files, hidden files, restarted my computer, etc and I'm still encountering this issue with no other non-default packages installed.

I'm running OSX 10.10.3, Atom 0.194.0 and language-fortran 1.5.1

**Comment by tomedunn** [comment]
I'm guessing this is related to issue #35. I feel like something in the [atom/firstmate](https://github.com/atom/first-mate) grammar engine must have changed to produce these crash issues.  Although it is possible I changed something in the grammar package to cause them. Most of the tests files I use are static so errors caused by dynamically typing could have gone unnoticed.

**Comment by tomedunn** [comment]
I've submitted a new pull request that fixes this issue (and hopefully any other unreported issues caused by the same bug). If you want to try it out to confirm the fix you can find it under pull request #38.

**Comment by kgerheiser** [comment]
That did the trick, thanks.

**Comment by tomedunn** [comment]
No problem. And thanks for reporting this bug! :smile:
