### ISSUE TITLE
colouring of module names

### ISSUE THREAD

**Issue by maxlevesque** [dparkins/language-fortran#61]
Hi there, once again : a big thank for all the efforts :), especially to you @tomedunn  !

Is this colouring correct?
![screenshot from 2015-10-19 17 07 56](https://cloud.githubusercontent.com/assets/1818339/10581664/35468950-7684-11e5-9641-da1d8f5ed347.png)

Modules names should be coloured, shouldn't they?

**Comment by tomedunn** [comment]
This is a little bit of a tricky subject. Technically both can be colored but the results will depend on your color theme. For instance, using the `Atom Dark` color theme both are highlighted as they both use the scope `entity.name` which is assigned a specific color
![AtomDark](https://cloud.githubusercontent.com/assets/5925666/10582225/6fce2d54-764c-11e5-8f43-56222a4666a0.PNG)

However many color themes don't assign a color to the scope `entity.name` and instead only assign a color to the more specific scope `entity.name.function`. You'll notice the subroutine name is given the scope `entity.name.function.subroutine` rather than `entity.name.subroutine`. This is to take advantage of this fact so that subroutine names and function names are colored the same regardless of what color theme you are using.

**Comment by maxlevesque** [comment]
Thanks a lot for the clear explanation.  
If I get it right, this is not an issue from language-fortran and it should be closed.

**Comment by tomedunn** [comment]
Yeah, probably the best solution for this is on the color scheme side. Thankfully, making a custom color scheme is pretty easy compared to making a custom grammar package! :smile:
