### ISSUE TITLE
index in do and do concurrent

### ISSUE THREAD

**Issue by maxlevesque** [dparkins/language-fortran#66]
Hi there,

![screenshot from 2015-10-27 11 36 52](https://cloud.githubusercontent.com/assets/1818339/10755637/2f971b3e-7c9f-11e5-8ccf-dd30d9d6b880.png)

Shouldn't `i` and `j` (index variables) have the same colour in do and do concurrent() ?

**Comment by tomedunn** [comment]
Yes, good catch. The parentheses in the `do concurrent` and `forall` constructs use the exact same rules as the parentheses for procedure and function calls. So the orange `j` in the `do concurrent` construct is being flagged as a procedure dummy variable rather than a loop control variable. I'll add an different one specifically for those construct.

**Comment by maxlevesque** [comment]
Also true for implicit array declaration, like in
```fortran
x(1:n) = [( i**2, i=1,n )]
```

**Comment by tomedunn** [comment]
@maxlevesque sorry for the delay. I've written up a fix for this but I got side-tracked by a new bug that I unearthed. I've been able to determine that bug didn't have anything to do with the changes I made to fix this so I will be uploading the changes and submitting a pull request later tonight.
