### ISSUE TITLE
end if

### ISSUE THREAD

**Issue by jacobwilliams** [dparkins/language-fortran#73]
Is it possible to disable the autocompletion of the `if` statement if it is proceeded by an `end`? Every time I type `end if` and hit Enter, it does the following, and then I have to undo.

<img width="231" alt="endif" src="https://cloud.githubusercontent.com/assets/6483379/11919194/62cd98ec-a711-11e5-8401-3c4e3e6a7ec4.png">

<img width="209" alt="endif2" src="https://cloud.githubusercontent.com/assets/6483379/11919200/a7c2107c-a711-11e5-9814-476eb5b5c088.png">

**Comment by tomedunn** [comment]
I haven't touched the snippets in a long while (maybe ever). So I'm not sure exactly what can be done with these other than to remove them. But I'll look into it and see if I can prevent them from triggering in these cases.

**Comment by tomedunn** [comment]
OK. After a few minutes playing with the rules it doesn't look like you can add regex to these rules. So place detecting doesn't seem possible. However I did learn that you can change Atom's autocomplete package `autocomplete-plus` to trigger using the `tab` key rather than `enter` ([see this post](https://discuss.atom.io/t/stop-enter-key-from-expanding-snippets-only-use-tab-key/19442)). That's probably the simplest solution.

**Comment by jacobwilliams** [comment]
That works for me. Thanks!
