### ISSUE TITLE
'Fortran - Fixed Form' highlights after column 72

### ISSUE THREAD

**Issue by crlsneng** [dparkins/language-fortran#81]
The 'Fortran - Fixed Form' grammar highlights even after column 72.  And the highlight seems to depend on the particular Fortran statement.

I recommend applying the comment highlight to anything after column 72.

Thanks.

![72column](https://cloud.githubusercontent.com/assets/4952536/19166608/cc6a09c4-8bcd-11e6-9a81-51127cd83c38.png)

**Comment by tomedunn** [comment]
Thanks for posting! I was able to throw together a quick partial fix to this issue that will hopefully be merged in soon. The fix at least addresses cases like the one you show in your example. It won't work in all cases however due to the way Atom handles grammar injections. From what I understand they are currently working on implementing an update to the grammar engine that should make a full fix possible soon though.

**Comment by crlsneng** [comment]
Thanks very much for your quick response.  Your fixes will be a good learning tool for me.
